### PR TITLE
 Increated timeouts

### PR DESCRIPTION
**Pull request by cdvultur**
Increasing timeout

### CODE REVIEW

**Comment by achuzhoy** [comment]
@cdvultur since DEFAULT_API_REQUEST_TIMEOUT is used in several places - could it be a real bug when the timeout takes too long to answer.

**Comment by cdvultur** [comment]
@achuzhoy Added the DEFAULT_CREATE_CLUSTER_BUTTON_SHOW_TIMEOUT to be more specific and not collide with the API ones.

**Review by nshidlin — APPROVED** [review]

**Pull request merged**
