### PR TITLE
add cypress-wait-until package

### PR DESCRIPTION
**Pull request by hardengl**

### CODE REVIEW

**Comment by hardengl** [comment]
@mareklibra @cdvultur I see many uses for this package in our current automation, let me know what y'all think.

**Comment by mareklibra** [comment]
Thanks for the contribution. I am ok with it as long as we will not misuse it. I would like to avoid heavy use of it on places where regular Cypress mechanisms can be used. Cases like chained waiting for multiple conditions make totally sense to me.

Can you please add typescript configuration? I saw that extra steps are needed.

**Comment by hardengl** [comment]
I will update the ts config. Yes, I agree to only use where needed.

**Review by mareklibra — APPROVED** [review]

**Pull request merged**
